# Generated by Django 2.0.7 on 2018-10-02 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='IdUsuario', primary_key=True, serialize=False)),
                ('loginusuario', models.CharField(blank=True, db_column='LoginUsuario', max_length=50, null=True, verbose_name='Login')),
                ('nomeusuario', models.CharField(db_column='NomeUsuario', max_length=50, verbose_name='Nome do Usuário')),
                ('ativo', models.BooleanField(db_column='Ativo')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'Usuario',
                'ordering': ['nomeusuario'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarioproduto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lider', models.BooleanField(db_column='Lider')),
            ],
            options={
                'verbose_name': 'Usuário Produto - Vinculação',
                'verbose_name_plural': 'Usuários Produtos - Vinculações',
                'db_table': 'UsuarioProduto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuariogrupo',
            fields=[
                ('idusuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.Usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário Grupo - Vinculação',
                'verbose_name_plural': 'Usuários Grupos - Vinculações',
                'db_table': 'UsuarioGrupo',
                'ordering': ['idusuario', 'idgrupo'],
                'managed': False,
            },
        ),
    ]
