# Generated by Django 2.1.1 on 2018-09-05 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('idequipe', models.AutoField(primary_key=True, serialize=False)),
                ('nomeequipe', models.CharField(max_length=50, verbose_name='Equipe')),
                ('equipeperfil', models.CharField(choices=[('DEV', 'Desenvolvimento'), ('SUS', 'Sustentação')], max_length=15, verbose_name='Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Permissoeslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(db_column='ambiente', max_length=20)),
                ('grupo', models.CharField(db_column='Grupo', max_length=50)),
                ('usuario', models.CharField(db_column='usuario', max_length=50)),
                ('lider', models.BooleanField()),
                ('produto', models.CharField(db_column='produto', max_length=50)),
                ('dbname', models.CharField(db_column='dbname', max_length=50)),
                ('typeoflogin', models.CharField(db_column='typeoflogin', max_length=50)),
                ('typeofrole', models.CharField(db_column='typeofrole', max_length=50)),
                ('permissionlevel', models.CharField(db_column='permissionlevel', max_length=50)),
            ],
            options={
                'verbose_name': 'Lista de Permissões',
                'verbose_name_plural': 'Lista de Permissões',
                'db_table': 'Permissoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idproduto', models.AutoField(primary_key=True, serialize=False)),
                ('nomeproduto', models.CharField(db_column='NomeProduto', max_length=50, verbose_name='Nome do Produto')),
                ('novaarquitetura', models.BooleanField(db_column='NovaArquitetura')),
                ('ativo', models.BooleanField(db_column='Ativo')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kerberosadm.Equipe')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'Produto',
                'ordering': ['nomeproduto'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produtosysdatabase',
            fields=[
                ('idprodutosysdba', models.AutoField(primary_key=True, serialize=False)),
                ('database_name', models.CharField(db_column='Database_name', max_length=100, verbose_name='Banco de Dados')),
                ('idproduto', models.ForeignKey(db_column='IdProduto', on_delete=django.db.models.deletion.DO_NOTHING, to='kerberosadm.Produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Banco vinculado a produto',
                'verbose_name_plural': 'Bancos vinculados a Produtos',
                'db_table': 'ProdutoSysDatabase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('idprojeto', models.AutoField(primary_key=True, serialize=False)),
                ('nomeprojeto', models.CharField(db_column='NomeProjeto', max_length=50)),
                ('ativo', models.BooleanField(db_column='Ativo')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kerberosadm.Equipe')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kerberosadm.Produto')),
            ],
            options={
                'db_table': 'Projeto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nomeusuario', models.CharField(max_length=50, verbose_name='Nome do Usuário')),
                ('loginusuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Login')),
                ('usuariotipo', models.CharField(choices=[('DOM', 'DOMINIO'), ('APP', 'APLICAÇÃO'), ('SERV', 'SERVIÇO')], max_length=10, verbose_name='Tipo')),
                ('ativo', models.BooleanField(db_column='Ativo')),
                ('descricao', models.TextField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'Usuario',
                'ordering': ['nomeusuario'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(to='kerberosadm.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='produtosysdatabase',
            unique_together={('idproduto', 'database_name')},
        ),
    ]
