# Generated by Django 2.1.1 on 2018-09-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerberosadm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='lider',
            field=models.BooleanField(db_column='Lider', default=False),
        ),
    ]
