# Generated by Django 2.1.1 on 2018-09-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerberosadm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariogrupo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usuariogrupo',
            name='idgrupo',
        ),
        migrations.RemoveField(
            model_name='usuariogrupo',
            name='idusuario',
        ),
        migrations.AddField(
            model_name='grupo',
            name='membros',
            field=models.ManyToManyField(to='kerberosadm.Usuario'),
        ),
        migrations.DeleteModel(
            name='Usuariogrupo',
        ),
    ]
