# Generated by Django 2.1.1 on 2018-09-05 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kerberosadm', '0002_auto_20180903_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuariogrupo',
            fields=[
                ('idusuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='kerberosadm.Usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário Grupo - Vinculação',
                'verbose_name_plural': 'Usuários Grupos - Vinculações',
                'db_table': 'UsuarioGrupo',
                'ordering': ['idusuario', 'idgrupo'],
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='membros',
        ),
        migrations.AlterField(
            model_name='produtogrupo',
            name='idproduto',
            field=models.ForeignKey(db_column='IdProduto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='kerberosadm.Produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='produtoprojeto',
            name='idproduto',
            field=models.ForeignKey(db_column='IdProduto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='kerberosadm.Produto'),
        ),
        migrations.AlterField(
            model_name='usuarioproduto',
            name='idusuario',
            field=models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='kerberosadm.Usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='usuariogrupo',
            name='idgrupo',
            field=models.ForeignKey(db_column='IdGrupo', on_delete=django.db.models.deletion.DO_NOTHING, to='kerberosadm.Grupo', verbose_name='Grupo'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariogrupo',
            unique_together={('idusuario', 'idgrupo')},
        ),
    ]
