# Generated by Django 2.0.7 on 2018-10-02 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idgrupo', models.AutoField(db_column='IdGrupo', primary_key=True, serialize=False)),
                ('nomegrupo', models.CharField(db_column='NomeGrupo', max_length=50, verbose_name='Nome do Grupo')),
                ('ativo', models.BooleanField(db_column='Ativo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'Grupo',
                'ordering': ['nomegrupo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idproduto', models.AutoField(db_column='IdProduto', primary_key=True, serialize=False)),
                ('nomeproduto', models.CharField(db_column='NomeProduto', max_length=50, verbose_name='Nome do Produto')),
                ('novaarquitetura', models.BooleanField(db_column='NovaArquitetura')),
                ('ativo', models.BooleanField(db_column='Ativo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'Produto',
                'ordering': ['nomeproduto'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtosysdatabase',
            fields=[
                ('idprodutosysdba', models.AutoField(primary_key=True, serialize=False)),
                ('database_name', models.CharField(db_column='Database_name', max_length=100, verbose_name='Banco de Dados')),
            ],
            options={
                'verbose_name': 'Banco vinculado a produto',
                'verbose_name_plural': 'Bancos vinculados a Produtos',
                'db_table': 'ProdutoSysDatabase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('idprojeto', models.AutoField(db_column='IdProjeto', primary_key=True, serialize=False)),
                ('nomeprojeto', models.CharField(db_column='NomeProjeto', max_length=50)),
                ('ativo', models.BooleanField(db_column='Ativo')),
            ],
            options={
                'db_table': 'Projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtogrupo',
            fields=[
                ('idproduto', models.ForeignKey(db_column='IdProduto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='kerberosadm.Produto', verbose_name='Produto')),
                ('ativo', models.BooleanField(db_column='Ativo')),
            ],
            options={
                'verbose_name': 'Produto - Grupo',
                'verbose_name_plural': 'Produtos - Grupos',
                'db_table': 'ProdutoGrupo',
                'ordering': ['idproduto', 'idgrupo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtoprojeto',
            fields=[
                ('idproduto', models.ForeignKey(db_column='IdProduto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='kerberosadm.Produto')),
                ('ativo', models.BooleanField(db_column='Ativo')),
            ],
            options={
                'verbose_name_plural': 'Produto - Projetos',
                'db_table': 'ProdutoProjeto',
                'managed': False,
            },
        ),
    ]
