# Generated by Django 2.0.7 on 2018-10-02 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kerberosadm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutogrupoTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_column='Ativo')),
                ('idgrupo', models.ForeignKey(db_column='IdGrupo', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='kerberosadm.Grupo', verbose_name='Grupo')),
                ('idproduto', models.ManyToManyField(to='kerberosadm.Produto')),
            ],
            options={
                'verbose_name': 'Produto teste - Grupo teste',
                'verbose_name_plural': 'Produtos teste - Grupos teste',
                'managed': True,
            },
        ),
    ]
