# Generated by Django 2.0.7 on 2018-10-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerberosadm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutogrupoTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_column='Ativo')),
            ],
            options={
                'verbose_name': 'Produto teste - Grupo teste',
                'verbose_name_plural': 'Produtos teste - Grupos teste',
                'db_table': 'ProdutoGrupo',
                'managed': False,
            },
        ),
    ]
