# Generated by Django 2.0.7 on 2018-10-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerberosadm', '0002_produtogrupoteste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtogrupoteste',
            options={'managed': False, 'ordering': ['idgrupo'], 'verbose_name': 'Produto teste - Grupo teste', 'verbose_name_plural': 'Produtos teste - Grupos teste'},
        ),
    ]
