# Generated by Django 2.0.7 on 2018-10-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerberosadm', '0003_auto_20181002_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtogrupoteste',
            options={'managed': False, 'verbose_name': 'Produto teste - Grupo teste', 'verbose_name_plural': 'Produtos teste - Grupos teste'},
        ),
    ]
