# Generated by Django 2.0.7 on 2018-10-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permissoeslist',
            table='PermissoesList',
        ),
    ]
