# Generated by Django 2.1.1 on 2018-09-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissoeslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(db_column='ambiente', max_length=20)),
                ('grupo', models.CharField(db_column='Grupo', max_length=50)),
                ('usuario', models.CharField(db_column='usuario', max_length=50)),
                ('lider', models.BooleanField()),
                ('produto', models.CharField(db_column='produto', max_length=50)),
                ('dbname', models.CharField(db_column='dbname', max_length=50)),
                ('typeoflogin', models.CharField(db_column='typeoflogin', max_length=50)),
                ('typeofrole', models.CharField(db_column='typeofrole', max_length=50)),
                ('permissionlevel', models.CharField(db_column='permissionlevel', max_length=50)),
            ],
            options={
                'verbose_name': 'Lista de Permissões',
                'verbose_name_plural': 'Lista de Permissões',
                'db_table': 'Permissoes',
                'managed': False,
            },
        ),
    ]
